// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FactoryData struct {
	Ts       int    `json:"ts"`
	Building string `json:"building"`
	Area     string `json:"area"`
	Value    int    `json:"value"`
}

type FirefightingData struct {
	Ts        int    `json:"ts"`
	Building  string `json:"building"`
	Floor     string `json:"floor"`
	Indicator string `json:"indicator"`
	Value     int    `json:"value"`
}

type Query struct {
}

type VendorOnmake struct {
	SupplyName   string `json:"supplyName"`
	SupplyCode   string `json:"supplyCode"`
	MaterialName string `json:"materialName"`
	MaterialType string `json:"materialType"`
	ProcessName  string `json:"processName"`
	OpID         *int   `json:"opId,omitempty"`
	Num          int    `json:"num"`
}
